services:
  nerbotix.api:
    image: nerbotix.api
    container_name: nerbotix.api
    build:
      context: .
      dockerfile: src/Nerbotix.Api/Dockerfile
    networks:
      - nerbotix_network
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=nerbotix.db;Port=5432;Database=${NERBOTIX_DB};Username=${NERBOTIX_DB_USER};Password=${NERBOTIX_DB_PASSWORD}
      SuperAdmin__Email: ${SuperAdminEmail}
      SuperAdmin__Password: ${SuperAdminPassword}
    depends_on:
      - nerbotix.db
    volumes:
      - /home/illia/diploma/data:/app/storage
    restart: always
  
  nerbotix.ui:
    image: nerbotix.ui
    container_name: nerbotix.ui
    build:
      context: ./src/Nerbotix.UI
      dockerfile: Dockerfile
    networks:
      - nerbotix_network
    ports:
      - "4200:80"
    depends_on:
      - nerbotix.api

  nerbotix.db:
    image: postgis/postgis
    container_name: nerbotix.db
    restart: always
    networks:
      - nerbotix_network
    environment:
      POSTGRES_DB: ${NERBOTIX_DB}
      POSTGRES_USER: ${NERBOTIX_DB_USER}
      POSTGRES_PASSWORD: ${NERBOTIX_DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "nerbotix"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

networks:
  nerbotix_network:
    driver: bridge
    name: nerbotix_network
    
volumes:
  pgdata:
  api-storage:
