using Nerbotix.Application.Common.Abstractions;

namespace Nerbotix.Application.Analytics.GetMonthTasksCreatedCount;

public record GetMonthTasksCreateCountAnalyticQuery : ITenantQuery<GetMonthTasksCreateCountAnalyticResponse>;