using Nerbotix.Application.Common.Abstractions;

namespace Nerbotix.Application.Analytics.GetRobotCountByCategories;

public record GetRobotCountByCategoriesAnalyticQuery : ITenantQuery<GetRobotCountByCategoriesAnalyticResponse>;